[package]
name = "diesel-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.5.3"
diesel = { version = "2.1.4", features = ["postgres", "uuid"] }
dotenvy = "0.15.7"
uuid = "1.7.0"
